### ISSUE TITLE
README examples contain errors

### ISSUE THREAD

**Issue by pandeiro** [thi-ng/validate#1]
Really like the ideas and simplicity behind this library, and I've started using it successfully. However I'm still trying to parse all of the semantics, especially involving nested data structures, and for that reason the README's examples (in lieu of other documentation) are especially important.

Here's the first example given:

``` clojure
(v/validate {:a "hello world"} :a (v/max-length 5 #(.substring % 0 5)))
```

That doesn't run:

```
ArityException Wrong number of args (3) passed to: core/validate  clojure.lang.AFn.throwArity (AFn.java:429)
```

Is this something that could be revised? I think it would be a big help. Thanks!

**Comment by postspectacular** [comment]
Thanks, @pandeiro! I completely forgot to update the code in the README, but pls do check the examples in the doc strings for `validate`. These should all work. And there're a couple of tests too.

Basically, the validation specs must be given as a map (not keyword args) and correction handlers now take 2 args,  so in your case (copied from doc string example):

``` clj
(v/validate
  {:a "hello world"}
  {:a (v/max-length 5 (fn [_ v] (.substring v 0 5)))})

;; => [{:a "hello"} nil]
```

Will update the readme asap

**Comment by pandeiro** [comment]
Awesome @postspectacular, thanks for the pointer to the docstrings and the additional explanation!

**Comment by postspectacular** [comment]
Updated the readme, please let me know if you spot any other issues. thx!
