### ISSUE TITLE
E-mail validation

### ISSUE THREAD

**Issue by pandeiro** [thi-ng/validate#2]
When I try to validate `foo@fuzz` with `(v/email)` no error is produced. Am I missing something or is this a bug?

**Comment by pandeiro** [comment]
The regex being used is `#"(?i)^[\w.%+-]+@[a-z0-9.-]+.[a-z]{2,6}$")`. Maybe what we want here is `#"(?i)^[\w.%+-]+@[a-z0-9.-]+\.[a-z]{2,6}$")` (escaping the dot in the middle)?

**Comment by postspectacular** [comment]
Good catch, thanks!

**Comment by pandeiro** [comment]
Cheers :+1:

**Comment by pandeiro** [comment]
Would a patch release be possible with this change?

**Comment by postspectacular** [comment]
almost there :)

**Comment by postspectacular** [comment]
done
